provides:
  - description: REST API
    service_name: uber-bill-print-service
    url: https://host:8443
    transportation_protocol: tcp
  - description: SOAP API (legacy)
    service_name: print-service
    url: http://host:80
    transportation_protocol: tcp

talks_to:
  - print-service
  - gateway-service
