service:
  provides:
    - description: REST API
      service_name: uber-bill-print-service
      protocol: https
      port: 8443
      transport_protocol: tcp
      public_dns:
       - api.demo-company.com
    - description: SOAP API (legacy)
      service_name: print-service
      protocol: http
      port: 80
      public_dns:
        - soap.demo-company.io
      transport_protocol: tcp

  depends_on:
    internal:
      - print-service
      - gateway-service
      - NGPS_8791
    external:
     - target: https://api.superdealz.me:443
       transport_protocol: tcp
       via: proxy-service
       why: Need to sync data with it.
     - target: mqtt://192.xxx.xxx.xxx:5028
       transport_protocol: tcp
       why: Get the latest Dealz.
