service:
  provides:
    - description: REST API
      service_name: uber-bill-print-service
      protocol: https
      port: 8443
      transportation_protocol: tcp
    - description: SOAP API (legacy)
      service_name: print-service
      protocol: https
      port: 80
      transportation_protocol: tcp

  external_connections:
     - target: https://api.superdealz.me:443
       transportationProtocol: tcp
       via: proxy-service
       why: Need to sync data with it.
     - target: mqtt://192.xxx.xxx.xxx:5028
       transportationProtocol: tcp
       why: Get the latest Dealz.

  talks_to:
    - print-service
    - gateway-service
